### ISSUE TITLE
Create user.

### ISSUE THREAD

**Issue by brayvasq** [kommitters/tickspot.js#64]
:information_source: This issue is part of the Epic #59.

### Objective
Create a module to create a user from the Tickspot API.

Documentation:
- [POST /users.json](https://github.com/tick/tick-api/blob/master/sections/users.md#create-user).

### CheckList
- [ ] Create a method to create a user.
- [ ] Create tests.

**Comment by SergioGueruiz** [comment]
Working on it :+1:
